// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABR5_McZuzdwOSxXqDG7YgcZNoLUKHND0',
    appId: '1:386697504013:web:f21da50fffdaa8ae993c44',
    messagingSenderId: '386697504013',
    projectId: 'mobileapp170-304f1',
    authDomain: 'mobileapp170-304f1.firebaseapp.com',
    storageBucket: 'mobileapp170-304f1.appspot.com',
    measurementId: 'G-2B4QYYERGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5pttQNgmzzHAI3MuwswyKXRLtujcQO18',
    appId: '1:386697504013:android:625fcece1bc9af6e993c44',
    messagingSenderId: '386697504013',
    projectId: 'mobileapp170-304f1',
    storageBucket: 'mobileapp170-304f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HADz9it_-p7Sdd-wd80aCZR4K_RzHd0',
    appId: '1:386697504013:ios:0af4da431e71933a993c44',
    messagingSenderId: '386697504013',
    projectId: 'mobileapp170-304f1',
    storageBucket: 'mobileapp170-304f1.appspot.com',
    androidClientId: '386697504013-0s00jmtr2ielb061pd0ss85ak2f0licg.apps.googleusercontent.com',
    iosClientId: '386697504013-7c56u2s0jm45cl6h18lf88uoiql4vv5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HADz9it_-p7Sdd-wd80aCZR4K_RzHd0',
    appId: '1:386697504013:ios:0af4da431e71933a993c44',
    messagingSenderId: '386697504013',
    projectId: 'mobileapp170-304f1',
    storageBucket: 'mobileapp170-304f1.appspot.com',
    androidClientId: '386697504013-0s00jmtr2ielb061pd0ss85ak2f0licg.apps.googleusercontent.com',
    iosClientId: '386697504013-7c56u2s0jm45cl6h18lf88uoiql4vv5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab07',
  );
}
